permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Portfolio"
  description: |
    Online portfolio for my graphic design work.
  font_url: "https://fonts.googleapis.com/css2?family=Gayathri:wght@100;400;700&family=Poppins:wght@200;300;400;500;600;700&display=swap"
  colors:
    sidebar: "--color-charcoal"
    accent: "--color-sea"
    background: "--color-cement"
    patterns:
      brand.logos: "--color-cement-light"
      buttons.basic: "--color-cement"
      buttons.glow: "--color-charcoal"
