patterns:
  work-preview:
    description: |
      The work-preview is used on the homepage to display each case study
    fields:
      - name: title
        type: string
        example: "Nature&#146s Care"
      - name: details
        type: string
        example: "logo design / branding"
      - name: description
        type: string
        example: "Nature&#146s Care is a local health product shop"
      - name: image
        type: image
        example: "natures-care-0.jpg"
      - name: data
        type: object
        data:
          source: "site.case-studies[0]"
          type: Project

  image-full:
    fields:
      - name: image
        type: image
        example: "natures-care-3.jpg"


  image-half:
    fields:
      - name: image
        type: image
        example: "natures-care-4.jpg"
      - name: image
        type: image
        example: "natures-care-4.jpg"
