patterns:
  work-preview:
    description: |
      The work-preview is used on the homepage to display content for each case study preview.
    fields:
      - name: title
        type: string
        example: "Nature’s Care"
      - name: details
        type: string
        example: "logo design / branding / statinery"
      - name: description
        type: string
        example: "Nature’s Care is a local health product shop"
      - name: data
        type: object
        data:
          source: "site.case-studies[0]"
          type: Project

  preview-img:
    description: |
      The preview-img is a preview image of the case study
    fields:
      - name: image
        type: image
        example: "natures-care-0.jpg"

  work-about:
    description: |
      The work-about section is used for introducting project details on case study pages.
    fields:
      - name: title
        type: string
        example: "Nature’s Care"
      - name: detail-1
        type: string
        example: "logo design"
      - name: detail-2
        type: string
        example: "branding"
      - name: detail-3
        type: string
        example: "stationery"
      - name: description
        type: string
        example: "Nature’s Care is a health product shop located in downtown Ottawa."
        data:
          source: "site.case-studies[0]"
          type: Project

  image-full:
    fields:
      - name: image
        type: image
        example: "natures-care-3.jpg"
        data:
          source: "site.case-studies[0]"
          type: Project

  image-half:
    fields:
      - name: image
        type: image
        example: "natures-care-4.jpg"
      - name: image
        type: image
        example: "natures-care-3.jpg"
        data:
          source: "site.case-studies[0]"
          type: Project
