patterns:
  work-preview:
    width: 100%
    description: |
      The work-preview is used on the homepage to display each case study
    fields:
      - name: data
        type: object
        data:
          source: "site.case-studies"
          type: Case Study
